Added fragment designs with its components
bchmsl/ChatApp pull request #1
Opened 2023-04-13 17:54 UTC by bchmsl

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 requested changes

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +
u can use supportFragmentManager.beginTransaction.apply{ 1st replace, 2nd replace}

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +
remove extra line

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/drawable/button_send.xml
> +        android:bottom="10dp"/>
u should create resource file for dp_s and sp_s and use it

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout-land/fragment_first_user.xml
> +        android:background="#F7CE7F"
move color into color resource file

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout-land/fragment_second_user.xml
> +        android:background="#F7CE7F"
here also

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_second_user.xml
> +        android:background="#F7CE7F"
here also, and every where u should replace hardcoded colors with color resource

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/layout_received.xml
> +
extra line

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/layout_sent.xml
> +
here also, pls format code and remove all extra lines

2023-04-13 18:08 UTC, GiorgiMamagulashvil1 commented
add ticket number and jira link in the pr

2023-04-13 18:30 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +
done

2023-04-13 18:30 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +
done

2023-04-13 18:30 UTC, bchmsl commented on app/src/main/res/drawable/button_send.xml
> +        android:bottom="10dp"/>
done

2023-04-13 18:30 UTC, bchmsl commented on app/src/main/res/layout-land/fragment_first_user.xml
> +        android:background="#F7CE7F"
done

2023-04-13 18:30 UTC, bchmsl commented on app/src/main/res/layout-land/fragment_second_user.xml
> +        android:background="#F7CE7F"
done

2023-04-13 18:30 UTC, bchmsl commented on app/src/main/res/layout/fragment_second_user.xml
> +        android:background="#F7CE7F"
done

2023-04-13 18:30 UTC, bchmsl commented on app/src/main/res/layout/layout_received.xml
> +
done

2023-04-13 18:30 UTC, bchmsl commented on app/src/main/res/layout/layout_sent.xml
> +
done

2023-04-13 18:36 UTC, iTarley approved these changes
seems good to me >_<

2023-04-14 13:03 UTC, Gio481 requested changes

2023-04-14 13:03 UTC, Gio481 commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-fragment:2.5.3'
მგონი ეს არ გჭირდება მაინც ერთი სქრინი გაქ

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +            replace(R.id.fcvSecond, SecondUserFragment(), null).commit()
ნალებს რატო აწოდებ რო მგონი არ გინდა

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(private val inflater: Inflater<VB>) : Fragment() {
კონსტრუქტოში ჩაწოდება გირჩევნია აბსტრაქტული იყოს და დააოვერაიდო, კოდის კითხვადობისთვის უკეთესი იქნება

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +    abstract fun start()
უკეთესი სახელი იქნება onBind

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/first_user/FirstUserFragment.kt
> +}
ვიუმოდელებიც დაამატე ბარემ თუ როდის აპირებ

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/drawable/scrollbar_track.xml
> +    <padding android:left="30dp" />
ყველა დპ და სპ უნდა გაიტონო დიმენშენების რესურსებში

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout-land/activity_main.xml
> +    android:background="?attr/background"
ბექრაუნდის ეს პარამეტრი რატო გინდა, რას შვება

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout-land/activity_main.xml
> +        android:name="androidx.navigation.fragment.NavHostFragment"
ესენიც არ გინდა

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout-land/fragment_first_user.xml
> +    tools:ignore="RtlSymmetry">
ეს იგნორი რატო დაგჭირდა წასაშლელია

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout-land/fragment_first_user.xml
> +            android:maxLines="5"
ამ შემთხვევაში ხო 5 ლაინზე მეტს ვერ დაწერ ? შენ გინდა რო 5 ზე მეტს რო დაწერს მერე გახდეს სქროლვადი

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout-land/fragment_first_user.xml
> +        android:layout_height="match_parent"
ამ დივაიდერის დანიშნულება ფრაგმენტების გაყოფაა ? თუ ესეა მაშინნ ექთივითიზე დასვი აქ არ უნდა იყოს

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout-land/fragment_second_user.xml
> +        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
იგივეები რაც პირველი უზერის ფრაგმენტზე დაგიწერე

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout-land/fragment_second_user.xml
> +        app:layout_constraintStart_toStartOf="parent" />
რატო გაქვს ორივე ფრაგმნეტზე დივაიდერის ვიუები, მაინ აქთივიზე დასვი

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout/layout_received.xml
> +    android:layout_marginEnd="120dp">
120 ით რატო გაქ დაშორებული

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout/layout_received.xml
> +        app:layout_constraintDimensionRatio="1"
ეს ატრიბუტი რას გიკეთებს, გჭირდება ?

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout/layout_received.xml
> +        tools:text="@string/sample_hello1" />
tools ის ტექსტების გატანა არ გინდა სტრინგებში

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout/layout_received.xml
> +    xmlns:tools="http://schemas.android.com/tools"
layout_received -> layout_received_item და იგივე sent ზეც რესაიქლერის აითემი ხოა და უკეთესი სახელია

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout/layout_sent.xml
> +    android:layout_marginStart="120dp"
აქაც მარჯინ სტარტი ამხელა რატოა, ამ შემთხვევაში ხო ამზე მეტს ვერ გაწევ რამხელა ტექსტიც უნდა დაწერო და სწორია ესე ?

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/layout/layout_sent.xml
> +        tools:text="@string/sample_long_text" />
დაამატე სტილები, სადაც გაუწერ რამდენიმე ვარიანტს ტექსვიუ და ედითტექტებისთვის სტილში გქონდეს, ფონტ საიზი, ქოლორი და ფონტ ფამილი და მაგ სტილებს დაუსეტავ ტექსტებს

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/values/dimensions.xml
> +    <dimen name="text_size_small">8sp</dimen>
სახელები ასე არ უნდა დაარქვა, dimen_28_dp და dimen_28_sp გადაარქვი და რომელ დპ და სპ გამოიტან შესაბამისად დაარქმევ

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/values/strings.xml
> +    <string name="sample_date_time">მარ 14, 16:00</string>
წასაშლელია ესსენი

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/res/drawable/button_send.xml
> +</layer-list>
ესენი კანვასზე არ უნდა დახატო ?

2023-04-14 13:03 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/first_user/FirstUserFragment.kt
> +class FirstUserFragment :
FirstUser da SecondUser რამდენად გაიგებ შენვე რომელია ზედა და რომელი ქვედა უფრო შესაბამისი სახელები რო დაარქვა ? მზია ზეზვა, ტოპ ბოთომ, ან სხვა რამეები :დ

2023-04-18 06:27 UTC, bchmsl commented on app/src/main/res/layout-land/activity_main.xml
> +    android:background="?attr/background"
თემებში მაქვს ბექგრაუნდის ფერი ატრიბუტად გატანილი და ეკრანის ბექგრაუნდს ცვლის დარქ მოუდის მიხედვით

2023-04-18 06:30 UTC, bchmsl commented on app/src/main/res/layout-land/fragment_first_user.xml
> +    tools:ignore="RtlSymmetry">
ეს იგნორი დასჭირდა TextIInputEditText-ს 43 ხაზზე (პადინგი გავუკეთე ბოლოში რომ გაგზავნის ღილაკი ჩამესვა) (endDrawable-თი სწორად ვერ სვამდა ფერებს გაგზავნის ღილაკზე)

2023-04-18 06:32 UTC, bchmsl commented on app/src/main/res/layout-land/fragment_first_user.xml
> +            android:maxLines="5"
კი, წერ 5 ლაინზე მეტს ჩვეულებრივად, უბრალოდ ამით ვაკონტროლებ რამდენი ხაზი ჩანდეს სანამ სქროლვა დაიწყება

2023-04-18 06:33 UTC, bchmsl commented on app/src/main/res/layout/layout_received.xml
> +    android:layout_marginEnd="120dp">
ჩათი სადაცაა აპლიკაციებში გამგზავნის და მიმღების მესიჯები ეკრანის მთლიან ნაწილს არ იკავებს სიგანეში და ამიტომ გავუკეთე გამგზავნს marginStart და მიმღებს marginEnd

2023-04-18 06:35 UTC, bchmsl commented on app/src/main/res/layout/layout_received.xml
> +        app:layout_constraintDimensionRatio="1"
სიგანეს და სიმაღლეს უფარდებს როგორც 1:1 და მარტივად შემიძლია გავადიდო და დავაპარატავო ერთი პარამეტრის შეცვლით (ამ შემთხვევაში width)

2023-04-18 06:36 UTC, bchmsl commented on app/src/main/res/layout/layout_received.xml
> +        tools:text="@string/sample_hello1" />
უბრალოდ დიდი და პატარა ტექსტების ტესტირებისთვის დამჭირდა, ვცვლიდი ხოლმე რომ დიდ და პატარა ტექსტებზე მომერგო და თუ არაა რეკომენდირებული, წავშლი

2023-04-18 06:37 UTC, bchmsl commented on app/src/main/res/layout/layout_sent.xml
> +    android:layout_marginStart="120dp"
კი, მაგაზე მეტად მარცხნივ არ გაიწევა, მაგრამ სიმაღლეში იზრდება (როგორც ყველა ჩატის აპლიკაციაში)

2023-04-18 06:38 UTC, bchmsl commented on app/src/main/res/drawable/button_send.xml
> +</layer-list>
არ იყო კანვასი სავალდებულო და მერე დავსერჩავ და გადავაკეთებთქო ვიფიქრე :D

2023-04-18 06:39 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/first_user/FirstUserFragment.kt
> +class FirstUserFragment :
ზედა და ქვედა რომ დავარქვა მერე Landscape-ში არ ჯდება კონტექსტში :D პირველი და მეორე პორტრეტის შემთხვევაში ზედა და ქვედაა და ლანდსქეიფის შემთხვევაში მარცხენა და მარჯვენა
(ზეზვას ფრაგმენტს და მზიას ფრაგმენტს არ ვიკადრებ :D :D)

2023-04-18 06:58 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/first_user/FirstUserFragment.kt
> +}
ბიზნესლოგიკაზე რომ გადავალ მერე დავამატებ ფრაგმენტებს და ცოტა წარმოდგენაც რომ შემექმნება სრული ფუნქციონალის იმპლემენტაციაზე :D

2023-04-18 07:24 UTC, Gio481 commented on app/src/main/res/layout/layout_received.xml
> +        tools:text="@string/sample_hello1" />
რეალურად ტყუილად აკავებინებ ადგილს ამ სტრინგს და წაშლა ჯობია 😃

2023-04-18 08:25 UTC, bchmsl commented on app/src/main/res/layout/layout_received.xml
> +        tools:text="@string/sample_hello1" />
ოქეი მაშინ წავშლი :D

2023-04-18 09:21 UTC, gioqemoklidze commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +            replace(R.id.fcvSecond, SecondUserFragment(), null).commit()
ეცადე ორივე უზერისთვის ერთი ფრაგმენტი გქონდეს და იმ ერთმა დაჰენდლოს გამგაზვნის შემთხვევაც და მიმღების შემთხვევაც

2023-04-18 09:21 UTC, gioqemoklidze commented on app/src/main/java/com/bchmsl/chatapp/presentation/first_user/FirstUserFragment.kt
> +class FirstUserFragment :
ზეზვა და მზია არ დაარქვა :D :D

2023-04-18 09:37 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +            replace(R.id.fcvSecond, SecondUserFragment(), null).commit()
@gioqemoklidze  მაგაზე ვფიქრობდი თავიდან და ბიზნესლოგიკაზე რო გადავალ მერე უფრო კარგად დავინახავ როგორ შეიძლება მაგის დაჰენდვლა და სავარაუდოდ მერე გადავაკეთებ

2023-04-18 09:50 UTC, bchmsl commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-fragment:2.5.3'
Done ✅

2023-04-18 09:50 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +            replace(R.id.fcvSecond, SecondUserFragment(), null).commit()
Done ✅

2023-04-18 09:50 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(private val inflater: Inflater<VB>) : Fragment() {
Done ✅

2023-04-18 09:50 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +    abstract fun start()
Done ✅

2023-04-18 09:50 UTC, bchmsl commented on app/src/main/res/drawable/scrollbar_track.xml
> +    <padding android:left="30dp" />
Done ✅

2023-04-18 09:50 UTC, bchmsl commented on app/src/main/res/layout-land/activity_main.xml
> +        android:name="androidx.navigation.fragment.NavHostFragment"
Done ✅

2023-04-18 09:50 UTC, bchmsl commented on app/src/main/res/layout-land/fragment_first_user.xml
> +        android:layout_height="match_parent"
Done ✅

2023-04-18 09:50 UTC, bchmsl commented on app/src/main/res/layout-land/fragment_second_user.xml
> +        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
Done ✅

2023-04-18 09:51 UTC, bchmsl commented on app/src/main/res/layout-land/fragment_second_user.xml
> +        app:layout_constraintStart_toStartOf="parent" />
Done ✅

2023-04-18 09:51 UTC, bchmsl commented on app/src/main/res/layout/layout_received.xml
> +        tools:text="@string/sample_hello1" />
Done ✅

2023-04-18 09:51 UTC, bchmsl commented on app/src/main/res/layout/layout_received.xml
> +    xmlns:tools="http://schemas.android.com/tools"
Done ✅

2023-04-18 09:51 UTC, bchmsl commented on app/src/main/res/layout/layout_sent.xml
> +        tools:text="@string/sample_long_text" />
Done ✅

2023-04-18 09:51 UTC, bchmsl commented on app/src/main/res/values/dimensions.xml
> +    <dimen name="text_size_small">8sp</dimen>
Done ✅

2023-04-18 09:51 UTC, bchmsl commented on app/src/main/res/values/strings.xml
> +    <string name="sample_date_time">მარ 14, 16:00</string>
Done ✅

2023-04-18 10:07 UTC, etozheluka commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +        }.commit()
I think it would be better to write a method for this

2023-04-18 10:07 UTC, iTarley commented on app/src/main/res/values/colors.xml
> +    <color name="divider">#F7CE7F</color>
try naming the colors by their names, with these names I can't tell what color it is (bubble_sent,bubble_recieved and etc.)

2023-04-18 10:09 UTC, iTarley commented on app/src/main/res/values/colors.xml
> +    <color name="divider">#F7CE7F</color>
also Camel case for color names is bad practice

2023-04-18 10:10 UTC, iTarley commented on app/src/main/res/values/colors.xml
> +    <color name="divider">#F7CE7F</color>
![image](https://user-images.githubusercontent.com/95241918/232745734-b3007b3a-86ee-40b2-a896-719fb7d96f6b.png)

2023-04-18 10:11 UTC, gioqemoklidze requested changes

2023-04-18 10:11 UTC, gioqemoklidze commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        return binding.root
if (_binding == null) {
            _binding = bindingInflater(inflater, container, false)
        }

        return _binding!!.root

2023-04-18 10:11 UTC, gioqemoklidze commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        return binding.root
დაგაზღვევს რო თუ ბაინდნგს აქვს მნიშვნელობა მეორედ აღარ მიენიჭოს

2023-04-18 11:57 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        return binding.root
ოქეი, ჩავამატებ, მაგრამ onCreateView ხო ყველა ვარიანტში onDestroyView-ს შემდეგ გამოიძახება მაინც? 🤔

2023-04-18 12:27 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +        }.commit()
Done ✅

2023-04-18 12:27 UTC, bchmsl commented on app/src/main/res/values/colors.xml
> +    <color name="divider">#F7CE7F</color>
Done ✅

2023-04-18 12:27 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        return binding.root
Done ✅

2023-04-18 12:31 UTC, GiorgiMamagulashvil1 approved these changes

2023-04-18 12:31 UTC, AleksandreGalogreBaramidze approved these changes

2023-04-18 12:35 UTC, gioqemoklidze commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        return binding.root
უფს ის არ შემიმჩნევია ონდისთროიში თუ ანალებდი ბაინდინგს მაშინ არაა საჭირო ეგ ჩეკი

2023-04-18 12:43 UTC, Gio481 approved these changes

2023-04-18 13:14 UTC, mariammnamgaladze approved these changes

2023-04-18 13:14 UTC, mariammnamgaladze commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
kargi bichi xar :* :D

2023-04-18 13:27 UTC, gioqemoklidze requested changes

2023-04-18 13:27 UTC, gioqemoklidze commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +            replace(R.id.fcvSecond, SecondUserFragment())
ამ შემთხვევაში add გამოიყენე replaceს მაგივრად, რადგან მხოლოდ ერთ ფრაგმენტს ვამატებთ ცარიელ კონტეინერში. ძალიან მინიმალური განსხვავებით, add უფრო სწრაფია, რადგან replaceს შემთხვევაში იმასაც ამოწმებ, კონტეინერში წინა ფრაგმენტი თუ არსებობს წასაშლელად
@AnaRusadze  დაგასწარი :D

2023-04-18 13:27 UTC, gioqemoklidze commented on app/src/main/res/layout/layout_received_item.xml
> +        android:layout_margin="3dp"
რესურსებში გაიტანე

2023-04-18 13:27 UTC, gioqemoklidze commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
ამას იყენებ რამეში ?

2023-04-18 13:30 UTC, gioqemoklidze requested changes

2023-04-18 13:30 UTC, gioqemoklidze commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
პრეზენთეიშენში გადააგდე მაინ ექთივითი

2023-04-18 13:35 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +            replace(R.id.fcvSecond, SecondUserFragment())
Done ✅

2023-04-18 13:35 UTC, bchmsl commented on app/src/main/res/layout/layout_received_item.xml
> +        android:layout_margin="3dp"
Done ✅

2023-04-18 13:35 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
Done ✅

2023-04-18 13:36 UTC, bchmsl commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Done ✅

2023-04-18 13:41 UTC, gioqemoklidze approved these changes

2023-04-18 13:42 UTC, AnaRusadze requested changes

2023-04-18 13:42 UTC, AnaRusadze commented on app/src/main/java/com/bchmsl/chatapp/MainActivity.kt
> +        }.commit()
როცა ფრაგმენტის ჩატვირთვა მარტო ერთხელ ხდება, შეგიძლია პირდაპირ add გამოიყენო replaceს ნაცვლად

2023-04-18 13:42 UTC, AnaRusadze commented on app/src/main/res/layout/layout_sent_item.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
განსხვავება send და receive აითემებში არის მარტო ფერი და scaleX (mirroring), დანარჩენი ყველაფერი იგივეა.
რესურსების ეკონომიისთვის შეგიძლია, ერთი ლეიაუთი ისე შექმნა, რომ ორივესთვის საკმარისი იყოს

2023-04-18 13:42 UTC, AnaRusadze commented on app/src/main/res/layout/layout_sent_item.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
https://stackoverflow.com/questions/36043905/how-to-mirror-a-textview ესეც გამოგადგება

2023-04-18 14:35 UTC, bchmsl commented on app/src/main/res/layout/layout_sent_item.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Done ✅

2023-04-19 09:11 UTC, AnaRusadze approved these changes

2023-04-19 09:11 UTC, merged