[CMOB-1310] Migrated to one fragment, added RecyclerView adapters and BroadcastReceiver
bchmsl/ChatApp pull request #2
Opened 2023-04-19 16:00 UTC by bchmsl

https://spaceneobank.atlassian.net/browse/CMOB-1310

ამ ბრენჩზე:
- შევქმენი RecyclerView-ს ადაპტერები, ჯერჯერობით ყველაფერი გავაკეთე სტატიკური ლისტით.
- აპლიკაცია გადავაკეთე ერთ ფრაგმენტზე
- დავამატე ვიუმოდელი
- დავამატე BroadcastReceiver მესიჯის გაგზავნა-მიღებისთვის

არსებული ბაგები:
- ეკრანის ამოტრიალების დროს ყველა მესიჯი ქრება და როდესაც მესიჯს გააგზავნი ახლიდან იტვირთება ძველი მესიჯებიც და ზემოდან ედება მესიჯების ახალი ლეიერი
- შესაძლოა მქონდეს memory leak-ებიც BroadcastReceiver-ის ნაწილში

პრ-ის პარალელურად გავფიქსავ ეკრანის ამოტრიალების დროს ბაგს და გავითვალისწინებ შენიშვნებს

ცალკე ბრენჩზე შემდეგ შემოვიტან domain და data ლეიერებს და გავაკეთებ Room-ით და Dependency Injection-ით.

2023-04-20 06:48 UTC, Gio481 requested changes

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/AndroidManifest.xml
> +        </receiver>
ბროდქასთი შეგიძლია მანიფესტშიც გქონდეს და კოდითაც დაწერო, განსხვავება ისაა რო თუ მანიფესტში გაუწერ ამ შემთხვევაში აპლიკაციის დაინსტალირების დროს ავტომატურად ესეც გაეშვება ხო და აპს რო ჩათიშავ ეს მაინც იქნება აქტიური და ხელმისაწვდომი ესე საჭიროა მაშინ როცა გინდა რო სხვა აპლიკაციისგან რაღაც შეტყობინება მიიღოს ამ აპლიკაციამ როცა ეს აპი არ გაქ გაშვებული და ყოველთვის ექნება რეაქცია და რეაგირება და როცა დინამიურად პროგრამულად რო ამატებ ეგ დინამიურია უკვე რანთაიმში დაარეგისტრირებ და წაშლი დარეგისტრირებულს და იმ კონკრეტულ მომენტში იქნება ხელმისაწვდომი როცა შენ გინდა რო იყოს ამ შემთხვევაში ზედმეტ რაღაცეებს აირიდებ თავიდან, ჩათ აპის შემთხვევაშიც ჩემი აზრით მხოლოდ კონკრეტული მომენტი გინდა რო აქტიური იყოს ბროდქასთი რო მიიღოს ივენთი და უმჯობესია პროგრამულად გაუწერო როდის შეიქმნას და როდის მოკვდეს ბროდქასთი

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/common/extensions/ContextExtensions.kt
> +    return dateFormat.format(Date())
Date() ამ მომენტის დროს გიჩვენებს ? შეგიძლია System.currentTimeMillis() ესეც გამოიყენო, ნუ თუ მუშაობს მაშინ იყოს :დ

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/MainActivity.kt
> +
ზოგადად კომპანიონ ობჯექტები ბოლოში იწერება ხოლმე მაგრამ ამ შემთხვევაში enum გამოიყენე სტრინგების მაგივრად

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +    abstract fun loadContent()
ვიუმოდელიც ბეისში შეაქმნივინე და აბსტრაქტული ფუნქცია იყოს onBindViewModel(viewModel) ანუ ფრაგმენტს ყველა ადგილიდიან ვიუმოდელზე წვდომა შეუზღუდე და ერთ კონკრეტულ ადგილას მოაქციე ვიუმოდელის რეფერენსების გასვლის მომენტი ამ შემთხვევაში onBindViewModel ფუნქცია იქნება ის მთავარი საიდანაც შიძლება ვიუმოდელს მიწვდე ასე იქნება უფრო სწორი პრაქტიკა და დალაგებული კოდი

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
> +    override fun onBindViewHolder(holder: FirstUserMessagesAdapter.ViewHolder, position: Int) {
ერთი ადაპტერი გამოიყენე

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
> +    inner class ViewHolder(private val binding: LayoutMessageItemBinding) :
ინერ კლასის გამოყენებამ შეიძლება მემორი ლიქამდე მიგიყვანოს და რატო, ამ შემთხვევაში ინერ კლას აქვს რეფერენსი ადაპტერის კლასთან და გარბიჯ კოლექტორი(ის რაც პასუხიმსგებელია გამოუყენებელი ობიექტების ანუ რეფერენსები რო აღარ აქვთ, წაშლაზე რო მემორი ლიქი არ მოხდეს) ვერ წაშლის ადაპტერის ობიექტს იმიტო რო ინერ კლასით რეფერენსი აქვს ადაპტერთან ამიტო ადაპტერის კლასი ვერ წაიშლება იქამდე სანამ ინერ კლასი იარსებებს

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
> +            val currentItem = getItem(adapterPosition)
შეგიძლია ქარენთ აითემი onBind ჩააწოდო პარამეტრად და onBindViewHolder იდან გადმოცე უფრო თვალსაჩინო რო იყოს რომელ მოდელს იყენებ

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
> +    }
ქოლბექსითვის ცალკე ჯენერიქ კლასი გააკეთე რომელიც ყველა ადაპტერზე იქნება მორგებული

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/MessagesReceiver.kt
> +    }
კომპანიონ ობჯექტი ბოლოს

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
ექსთენშენი გააკეთე ამის

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserFragment.kt
> +                    binding.rvMessageHistory.scrollToPosition(MessageUiModel.messagesTestList.lastIndex)
აქ შეგიძლია ასე დაწერო adapter.itemCount -1

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserFragment.kt
> +    }
ბეის ფრაგმენტის მიზანია რო რაც ძირითადი და საერთოა იქ გქონდეს გატანილი ამიტო ბროდქასთის შექმნა და წაშლაც იქ გაიტანე

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserViewModel.kt
> +    }
ვიუმოდელ სკოუპი არ უნდა ამას და ეს ფუნქცია არცაა ვმ ში საჭირო

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserFragment.kt
> +
ეს ლოგიკები ვმ ში გაიტანე რო ფრაგმენტი რაც შეიძლება სუფთა იყოს

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserViewModel.kt
> +
ბროდქასთისთვისაც გააკეთე ერთი ასეთი და ფრაგმენტიდან რო დააქოლექთებ მერე გაუშვი ბროდქასთი

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/model/MessageUiModel.kt
> +    }
ეს კომპანიონი წასაშლელია

2023-04-20 06:48 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
ფექიჯებად გაქ დასაყოფი, უსერის ფოლდერი არაა შესაბამისი chat დაარქვი და ფრაგმენტსაც ChatFragment ადაპტერსაც თავისი ფოლდერი გაუკეთე პრესენთეიშენის გარეთ შეგიძლია გააკეთო ფოლდერი service და იქ გქონდეს ბროდქასთი

2023-04-20 06:53 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserViewModel.kt
> +    }
ეს უბრალოდ სატესტოდ გავიტანე, როცა რუმს დავამატებ მაინც ხო დამჭირდება ვმ-ში დაწერა და სკოუპიც დამჭირდება და მაგიტო დავწერე სკოუპში

2023-04-20 06:54 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserViewModel.kt
> +        viewModelScope.launch {
viewModelScope.launch ექსთენშენიც გააკეთე ნუ შეიძლება ისეთი არაფერი მარა ყოველ ჯერზე .launch წერის მაგივრად ერთ სიტყვიანი რო იყოს viewModelScope{} მაგალითად უკეთესი იქნება :დ

2023-04-20 06:55 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/model/MessageUiModel.kt
> +    }
ჯერჯერობით სატესტოდ მაქვს და იყოს ამ ბრენჩზე, ახალ ბრენჩზე ვაპირებ ამ პრ-ს შემდეგ რუმის შემოტანას და ამ კომპანიონსაც გავაქრობ

2023-04-20 06:59 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserViewModel.kt
> +    }
ხო მარა როცა რუმს გამოიყენებ მაშინ დაწერე ესეც, მაგალითად ჩემი აზრით ჯობია რო ჯირაზე რაც დაარეგისტრირე ტასკი ეგ გააკეთო სადაც ვთვქათ არ გექნება ისეთი ფუქნციები რომლებიც უეჭველი უნდა წაშალო ან შეცვალო მთლიანად შემდეგ პრებზე, მთავარი არაა რო მეორე პრზევე გატესტო და იმუშაოს ნელ ნელა სუფთა კოდით პატარ პატარა პრებით მიიყვან იმ კონდიციებამდე რო გატესტავ და მერე ბაგებს დაარეგისტრირებ და იმას გაასწორებ და უფრო დაგეზოგება დრო ვიდრე ეხლა ისეთი რამეები დაწერო რაც მერე არ უნდა გამოიყენო შეილება უფრო აგირიოს რაღაცეები

2023-04-21 16:40 UTC, bchmsl commented on app/src/main/AndroidManifest.xml
> +        </receiver>
Done ✅

2023-04-21 16:40 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/common/extensions/ContextExtensions.kt
> +    return dateFormat.format(Date())
Done ✅

2023-04-21 16:40 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/MainActivity.kt
> +
Done ✅

2023-04-21 16:40 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +    abstract fun loadContent()
Done ✅

2023-04-21 16:41 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
> +            val currentItem = getItem(adapterPosition)
Done ✅

2023-04-21 16:41 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/MessagesReceiver.kt
> +    }
Done ✅

2023-04-21 16:41 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
Done ✅

2023-04-21 16:41 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserFragment.kt
> +                    binding.rvMessageHistory.scrollToPosition(MessageUiModel.messagesTestList.lastIndex)
Done ✅

2023-04-21 16:41 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserFragment.kt
> +    }
Done ✅

2023-04-21 16:41 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserViewModel.kt
> +    }
Done ✅

2023-04-21 16:41 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserFragment.kt
> +
Done ✅

2023-04-21 16:42 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
Done ✅

2023-04-21 16:42 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserViewModel.kt
> +        viewModelScope.launch {
Done ✅

2023-04-21 19:26 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/UserViewModel.kt
> +
ამას ცოტა ვერ მივხვდი,
როდესაც ფრაგმენტში ლისთს დავაქოლექთებ მერე რისთვის მინდა ბროდქასთი?

2023-04-21 19:27 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
> +    override fun onBindViewHolder(holder: FirstUserMessagesAdapter.ViewHolder, position: Int) {
Done ✅

2023-04-21 19:27 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
> +    inner class ViewHolder(private val binding: LayoutMessageItemBinding) :
Done ✅

2023-04-21 19:27 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/user/FirstUserMessagesAdapter.kt
> +    }
Done ✅

2023-04-22 10:27 UTC, Gio481 requested changes

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/model/MessageUiModel.kt
> +    val sentDate: String,
date უმჯობესია შეინახო როგორც Long, იმიტირო ახლა სტრინგად რო ინახავ და რო გითრხა რო მარტო საათი გამოაჩინე თქო რას იზავ

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/model/ModelWithId.kt
> +}
ეს რას გიკეთებს რატო გინდა დიფუტილში პირდაპირ oldItem.hascode  რო დაწერო ?

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/common/extensions/FragmentExtensions.kt
> +fun Fragment.async(lifecycleState: Lifecycle.State = Lifecycle.State.RESUMED, block: suspend ()-> Unit){
async გაუგებარი სახელია, შეგიძლია executeASync დაარქვა ან უკეთესი სახელს თუ მოიფიქრებ კაი იქნება :დ

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/common/extensions/ViewModelExtensions.kt
> +fun ViewModel.async(
აქაც იგივე

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/common/providers/DateProvider.kt
> +}
დეითის სტრინგად შენახვაზე რო დაგიწერე შესაბამისად ესეც long ექსთენშენი გააკეთე და დაფორმატებულს კი არ შეინახავ როგორც გინდა ისეთ დაფორმატირებულს დაახატინებ

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +class ChatAdapter(private val user: UserTags?) :
ნალეიბლი რატო?

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +        }
ეს ყველაფერი ვიუჰოლდერში უნდა იყოს და ასეთი ლოგიკა შეგიძლია ჩადო, isSentByFirstUser ეს ამოუღო მოდელ კლასიდან და UserTags ჩააწოდო და ამ UserTags ით გაასხვავებ როგორ დაიხატოს

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +                    }
აქ this მიანიჭებ თუ 1f ხო არაფერ გამარტივებას გაძლევს ასეთ მომენტებში ფაქტობრივად აზრი არ აქვს with გამოყენებას

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +                    }
ერთი ფუნქცია გააკეთე ცალკე ქოლორის და სქეილის და ეგ გამოიყენე და როგორც გითხარი ვიუჰოლდერში

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding, VM : ViewModel, BR : BroadcastReceiver>() :
ბროდქასთის აქ ჩაწოდება არ გინდა შეგიძლია ეგეც აბსტრაქტული ფუნქცია ან ცვლადი ან open იყოს იმიტო რო იზრდება ფრაგმენტის ჯენერიქობაც და კი აქ მარტო ერთი სქრინია მარა შენ ჯენერალად უნდა იფიქრო ზოგადად და სხვა სქრინი რო დაემატოს სადაც ბროდქასთი  არ გინდა მერე რას იზავ

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        requireActivity().registerReceiver(receiver, filter)
ასეთი რამის გაკეთება შეგიძლია ცადო,  აბსტრაქული კლასი რო გააკეთო ბროდქასთის შვილი, აბსტრაქული ცვლადით actionName, მერე მაგ კლასის ტიპის რო იყოს რესივერი და შენი ქასთუმ რესივერი რო მიანიჭო, და ამის მსგავსად რო გააკეთო, ინტენრ ფილტერის ოვერაიდიც რო არ დაგჭირდეს, აბა ცადე თუ გამოვა
![br](https://user-images.githubusercontent.com/70803715/233777200-681f3e2c-9c68-496a-aed9-0255efc895df.PNG)

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        requireActivity().sendBroadcast(intent)
ესეც აღარ დაგჭირდება აქ ისე თუ გამოვა მაღლა რო გითხარი

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +    abstract fun loadContent(vm: VM)
ჯობია აბსტრაქტული იყოს onBindViewMoldel(vm: VM) და ლოადკონტენტი და ლისენერის ფუნქცია ჩათის ფრაგმენტშივე შექმენი

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        requireActivity().registerReceiver(receiver, filter)
onCreateView ბაინდინგს დახატავს და ვმ და ბროქასთის რეგისტრაცია onCreate ში ქენი

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/model/UserTags.kt
> +}
First_User_TAG -> FirstUser და მეორეზეც, ტაგს ისეც კლასის სახელი აღნიშნავს

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +    private val userMessagesAdapter by lazy { ChatAdapter(tag?.let { UserTags.valueOf(it) }) }
ადაპტერს პირდაპირ ტაგი რო ჩააწოდო რა განსხვავებას მოგცემს ?

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +            }
postDelayed მაგივრად კორუტინის delay გამოიყენე ხოლმე მარა ეს გიკეთებს იმას რო მაღლა რო გაქ ასქროლილი მესიჯი რო დაწერო დაბლა ჩამოსქროლოს თუ რაშვება, თუ ეგრეა stackFromEnd ეს გამოიყენებ ნახე აბა რასიზავს

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                binding.rvMessageHistory.scrollToPosition(userMessagesAdapter.itemCount - 1)
ქოლექთის დროს ეს რას შვება რატო გინდა ?

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                userMessagesAdapter.submitList(MessageUiModel.messagesTestList.toList())
ეხლა ხო async და მერე collect გაქ და ექსთენშენი თუ გაკეთდება რო პირდაპირვე collectData რო იყოს ან რამე მსგავსი სახელით და ეს გაგიკეთოს

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                )
ეს ჩეკიც ვმში გქონდეს და მოდელზე როგორც გითხარი UserTags გქონდეს და ასე უნდა გააკეთო, btnSend რო დააწვები მხოლოდ გამოიძახო vm.sendMessage და hideKeyboard sendMessage-მ ივენთი უნდა გაუშვას რასაც დაობსერვებ, დააქოლექთებ და იმ ქოლექთის დროს გაუშვებ ბროდქასთს

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/res/values/colors.xml
> +    <color name="dark_01">#160039</color>
უფრო შესაბამისი სახელები დაარქვი ფერებს

2023-04-22 10:27 UTC, Gio481 commented on app/src/main/res/layout/fragment_user.xml
ამასაც შეუცვალე სახელი

2023-04-24 13:12 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +class ChatAdapter(private val user: UserTags?) :
რადგან ფრაგმენტის ფროფერთი tag არის String? და ფრაგმენტში რომ არ დამეწყო შემოწმებები და ბევრჯერ არ მეწერა .let ადაპტერში გავიტანე

2023-04-24 13:13 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +        }
ვიუჰოლდერში ვცადე, მაგრამ რადგან ინერ კლასს ვერ ვიყენებ ვიუჰოლდერად ლისტზე წარმოდგენა არ აქვს ვიუჰოლდერს და getItem-ს ვერ ვიძახებ :(

2023-04-24 13:14 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +                    }
იდეურად არ აქვს მნიშვნელობა, მაგრამ შეცვლა რომ დაგვჭირდეს ერთ ადგილას შევცვლით და სამივეზე გავრცელდება

2023-04-24 13:49 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +    private val userMessagesAdapter by lazy { ChatAdapter(tag?.let { UserTags.valueOf(it) }) }
შემდეგ ნებისმიერი სტრინგის ჩაწოდება შეგვეძლება, რაც არასწორი მგონია,
ასე კონკრეტულადაა გაწერილი რა ტიპი უნდა ჩავაწოდო

2023-04-24 14:58 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +    abstract fun loadContent(vm: VM)
ანუ vm ფრაგმენტის ფროფერთიდ არ მქონდეს გამოტანილი და სადაც დამჭირდება პარამეტრებით გავატანო ყველგან?

2023-04-24 17:53 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/model/MessageUiModel.kt
> +    val sentDate: String,
Done ✅

2023-04-24 17:53 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/model/ModelWithId.kt
> +}
Done ✅

2023-04-24 17:53 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/common/extensions/FragmentExtensions.kt
> +fun Fragment.async(lifecycleState: Lifecycle.State = Lifecycle.State.RESUMED, block: suspend ()-> Unit){
Done ✅

2023-04-24 17:53 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/common/extensions/ViewModelExtensions.kt
> +fun ViewModel.async(
Done ✅

2023-04-24 17:54 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/common/providers/DateProvider.kt
> +}
Done ✅

2023-04-24 17:54 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +        }
Done ✅

2023-04-24 17:54 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +                    }
Done ✅

2023-04-24 17:54 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +                    }
Done ✅

2023-04-24 17:55 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        requireActivity().registerReceiver(receiver, filter)
Done ✅

2023-04-24 17:55 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/model/UserTags.kt
> +}
Done ✅

2023-04-24 17:55 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +            }
Done ✅

2023-04-24 17:56 UTC, bchmsl commented on app/src/main/res/values/colors.xml
> +    <color name="dark_01">#160039</color>
დიზაინში იყო მოცემული ფერების სახელები

2023-04-24 17:56 UTC, bchmsl commented on app/src/main/res/layout/fragment_user.xml
Done ✅

2023-04-24 17:57 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                binding.rvMessageHistory.scrollToPosition(userMessagesAdapter.itemCount - 1)
ქვევით სქროლავს რისაიქლერს მესიჯების ჩატვირთვის დროს

2023-04-25 10:41 UTC, Gio481 requested changes

2023-04-25 10:41 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +    }
გააერთიანე ბარემ ეს ორი ფუნქცია

2023-04-25 10:41 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +
ვიუჰოლდერის კლასი სუ ბოლოს დაწერე ხოლმე

2023-04-25 10:41 UTC, Gio481 commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +                    )
მესიჯის მოდელში რო შეინახო UserTags ტიპის ცვლადი და აქ დაგჭირდება მარტო მაგის შემოწმება რო უსერ თუ მესიჯის მოდელში შენახული იუზერია მაშინ გაგზავნის მესიჯი დახატოს თუარადა მეორე ნაირი, ესე ცადე ამის გაკეთება

2023-04-25 10:42 UTC, Gio481 commented
@bchmsl რაც დარესოლვებული არ მაქ ეგენი გაასწორე და ჩემგან ეფრუვ

2023-04-25 11:48 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +    }
ვცადე მაგრამ არ გამოვიდა,
სხვადასხვა ვიუებზე მჭირდება scale და tint

2023-04-26 10:38 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                delay(100)
შეგიძლია დილეის დრო კონსტანტად გაიტანო, რაში დაგვეხმარება ეს?  მომვალაში შესაძლოა მოგიწიოს რამოდენიმე ადგიალს ერთი და იგივე დილეის დაყენება, და ყველგან სათითაოდ უნდა ცვალო ეს პარამეტრი. კონსტანტური ცვლადის შემთხვევაში, მხოლოდ ამ კონსტანტურ ცვლადს შეცვლი ერთხელ.

2023-04-26 12:48 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding, VM : ViewModel, BR : BroadcastReceiver>() :
ვცადე და მგონი რაღაც გამოვიდა :D იმას სჯობს რაც იყო

2023-04-26 12:49 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        requireActivity().registerReceiver(receiver, filter)
Done ✅

2023-04-26 12:49 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/base/BaseFragment.kt
> +        requireActivity().sendBroadcast(intent)
Done ✅

2023-04-26 12:56 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                )
ანუ ვიუმოდელში ფუნქციას ვიუები გავატანო? თუ როგორ მქონდეს ეგ ჩეკი ვმში?

2023-04-26 13:26 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                userMessagesAdapter.submitList(MessageUiModel.messagesTestList.toList())
Done ✅

2023-04-26 13:26 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                )
Done ✅

2023-04-26 13:26 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +
Done ✅

2023-04-26 13:26 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/adapter/ChatAdapter.kt
> +                    )
Done ✅

2023-04-26 13:26 UTC, bchmsl commented on app/src/main/java/com/bchmsl/chatapp/presentation/ui/chat/ChatFragment.kt
> +                delay(100)
Done ✅

2023-04-26 17:31 UTC, Gio481 approved these changes

2023-05-01 08:47 UTC, AnaRusadze approved these changes

2023-05-01 09:03 UTC, GiorgiMamagulashvil1 approved these changes

2023-05-01 09:10 UTC, merged