[CMOB-1361] Adapter Abstraction
bchmsl/ChatApp pull request #4
Opened 2023-05-02 11:02 UTC by bchmsl

დავამატე BaseAdapter, ადაპტერი დამოკიდებულია აბსტრაქციაზე UserId-ების შესახებ ზურას მოთხოვნისამებრ.

2023-05-02 13:15 UTC, Gio481 requested changes

2023-05-02 13:15 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/BaseAdapter.kt
> +    }
ინტერფეისი ცალკე გაიტანე

2023-05-02 13:15 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/presentation/base/fragment/BaseFragment.kt
> +
ამდენი უზერ აიდი რა არი :დ ინტერფეისი კონტრაქტორად აქ გაუკეთე ბეის ფრაგმენტს და შვილს დაამპლემეტირებინე და მეტი არაფერი იუზერ აიდები დაგჭირდება

2023-05-02 13:15 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/adapter/ChatAdapter.kt
> +            }
რუთზე შეგიძლია ლეიაუთ დირექშენი გამოიყენო და არ დაგჭირდება ეს ფუნქცია

2023-05-02 13:15 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/adapter/ChatAdapter.kt
> +        )
ამის თავში დაწერა უმჯობესი იქნება

2023-05-02 13:15 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/fragment/ChatFragment.kt
> +            binding.chatRecyclerView.scrollToPosition(messages.size - 1)
კოტლინის ექსთენშენი გამოიყენე -1 მაგივრად

2023-05-02 13:15 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/vm/ChatViewModel.kt
> +    fun sendMessage(etMessage: Editable, user: String) {
editable მაგივრად პირდაპირ სტრინგი რო გქონდეს

2023-05-02 13:15 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/BaseAdapter.kt
> +    }
რა მოხდება ისეთ ადაპტერს თუ შექმნი რომელსაც AdapterListener არ დაჭირდება, ანუ უეჭველი ერთი ადაპტერისთვის გააკეთე ბეიზი ?

2023-05-02 14:15 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/adapter/ChatAdapter.kt
> +            }
მერე სხვანაირად კეთდება და შესაცვლელი მექნება რაღაცები, დიზაინის ბრენჩზე მომიწევს გადასვლა ისევ მაშინ, იყოს ამ მიდგომით :D

2023-05-02 14:19 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/BaseAdapter.kt
> +    }
არა, ამ აპლიკაციაში არ მჭირდება და ლისენერიანი ადაპტერისთვის გავაკეთე

2023-05-02 14:21 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/BaseAdapter.kt
> +    }
Done ✅

2023-05-02 14:21 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/base/fragment/BaseFragment.kt
> +
ცოტა სხვანაირად, მაგრამ Done ✅

2023-05-02 14:21 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/fragment/ChatFragment.kt
> +            binding.chatRecyclerView.scrollToPosition(messages.size - 1)
Done ✅

2023-05-02 14:21 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/vm/ChatViewModel.kt
> +    fun sendMessage(etMessage: Editable, user: String) {
Done ✅

2023-05-02 14:44 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/common/extensions/RecyclerViewExtensions.kt
> +}
კოტლინს აქვს ექსთენშენი dec() და ეგ ვიგულისხმე :დ

2023-05-02 14:55 UTC, Gio481 commented on app/src/main/java/com/space_intl/chatapp/presentation/base/fragment/BaseFragment.kt
>      }
abstract class BaseFragment<VB : ViewBinding, VM : ViewModel> : Fragment(), AdapterListener 
გაუკეთე და აქ არ დააოვერაიდო და შვილს კიდე მასტ ოვერაიდი ექნება და მაგ ფუნქციას გამოიყენებ vm.sendMessage() ში

2023-05-02 15:15 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/common/extensions/RecyclerViewExtensions.kt
> +}
უი, ძაან შორს წავედი :D მარა ესეც კაია, მაგასაც დავამატებ

2023-05-02 15:18 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/base/fragment/BaseFragment.kt
>      }
ხო მარა ამის მუღამი ისაა რო შვილში ოვერრაიდი აღარ დამჭირდეს, თავისით იღებს getter-ით (ახალ კომიტში ვამატებ) შვილის ტაგს და მაგითი მუშაობს

2023-05-02 15:20 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/base/fragment/BaseFragment.kt
>      }
თან ანონიმური ობიექტი მჭირდება რო ადაპტერს გავატანო

2023-05-03 08:07 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/BaseAdapter.kt
> +    }
Done ✅

2023-05-03 08:08 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/adapter/ChatAdapter.kt
> +        )
Done ✅

2023-05-03 08:13 UTC, AleksandreGalogreBaramidze requested changes

2023-05-03 08:13 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/adapter/ChatAdapter.kt
> +                    if (isSentMessage) 1f else -1f,
გაიტანე კონსტანტებში ეს ორი ფლოუთი და ლოგიკური სახელი დაარქვი, რადგან უფრო კითხვადი იყოს დეველოპერისთვის. სხვა ადამიანს რომ აქ ცვლილება მოუწიოს, რესერჩი დაჭირდება ამ შემთხვევაში, როცა ნეიმინგი გექნება ამ მნიშვნელობებზე ნაკლები დრო წავა იმის გარკვევაში, რას ემსახურება ეს.

2023-05-03 08:15 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/adapter/ChatAdapter.kt
> +                    if (isSentMessage) 1f else -1f,
ახალი ბრენჩი სადაც გავაკეთე ინტერნეტის ჩეკისთვის მანდ მაქვს გატანილი უკვე 🫡

2023-05-03 08:18 UTC, shioandghuladze requested changes

2023-05-03 08:18 UTC, shioandghuladze commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/AdapterListener.kt
> +    fun getUserId(): String
ლამბდა გამოიყენე 1 ფუნქციანი ინტერფეისის ნაცვლად

2023-05-03 08:18 UTC, shioandghuladze commented on app/src/main/java/com/space_intl/chatapp/presentation/activity/ChatActivity.kt
> +    private fun switchListener() {
setSwitchListener

2023-05-03 08:18 UTC, shioandghuladze commented on app/src/main/java/com/space_intl/chatapp/common/extensions/ActivityExtensions.kt
> +            add(container.id, fragment, container.id.toString())
ზოგადად თეგით ასეთი რაღაცეების დაჰენდლვა (გარკვევა თუ რომელი იუზერის ეკრანია) არ არის კარგი, მაგრამ თეგად ვიუს აიდის გამოყენება უარესია 😄 ეცადე რომ თეგისთვის შეუქმნა ექსთენშენს კიდევ ერთი პარამეტრი და ცალკე ჩამოაწოდო რამე ენამი ან სტრინგი როგორც სხვებს აქვთ.

2023-05-03 08:19 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/AdapterListener.kt
> +    fun getUserId(): String
ზურას ახსნიდან მუღამი ის იყო რო აბსტრაქციაზე უნდა გვქონოდა დამოკიდებული ;დ

2023-05-03 08:24 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/activity/ChatActivity.kt
> +    private fun switchListener() {
Done ✅

2023-05-03 08:24 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/common/extensions/ActivityExtensions.kt
> +            add(container.id, fragment, container.id.toString())
Done ✅

2023-05-03 08:32 UTC, shioandghuladze commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/AdapterListener.kt
> +    fun getUserId(): String
ლამბდა ზუსტად იგივეა განმარტებით - 1 ფუნქციანი ინტერფეისი 😄 ლისენერების ასე დადება ცოტა ძველი მოდაა :დ

2023-05-03 08:44 UTC, bchmsl commented on app/src/main/java/com/space_intl/chatapp/presentation/base/adapter/AdapterListener.kt
> +    fun getUserId(): String
Done ✅

2023-05-03 08:49 UTC, shioandghuladze approved these changes

2023-05-03 12:02 UTC, AleksandreGalogreBaramidze approved these changes

2023-05-03 12:52 UTC, mariammnamgaladze requested changes
ujas, chems kodshi wminda rame datove? ))))))))))

2023-05-03 12:52 UTC, mariammnamgaladze commented on app/src/main/java/com/space_intl/chatapp/presentation/base/fragment/BaseChatFragment.kt
>      }
ctrl+alt+l

2023-05-03 12:52 UTC, mariammnamgaladze commented on app/src/main/java/com/space_intl/chatapp/presentation/ui/chat/adapter/ChatAdapter.kt
>              with(binding) {
ctrl+alt+l

2023-05-03 12:55 UTC, mariammnamgaladze approved these changes

2023-05-03 15:06 UTC, Gio481 approved these changes

2023-05-04 14:10 UTC, merged